* Repository containing files for modifying xopp files.
** DONE git-xopp.sh - This file contains sh script for using git with xournalpp.
** TODO change_page_no.bash - If new pages are added to PDF before the page annotated in xournalpp, this creates discrepancy as the pages in pdf increase and the annotations remain on the original page no so they do not correspond to new pages. With this script we can change page no of the page containing annotation and of subsequent pages.
*** Map of all the things that need to be done in the form of an example, suppose pg no 103 needs to be converted to pg no 107 in a xopp file with total pages 498, then: [0/4]
+ [ ] Add entry for pg no 103-106 before pg entry 103;
+ [ ] check the last pg no in the file i.e. pg 498 save it as an variable;
+ [ ] start chenging pg entry 103-104 and then do likewise with all next page entries till last page (pg no 498);
  - a problem arises as now pg 103 is there twice and both will be changed; [0/1]
    * +either make two files from initial file and then join them afterwards;+
    * [ ] or first change pg nos then add missing entries
+ [ ] Check if everything works and add exit codes.
